# Generated by Django 5.2 on 2025-04-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meteorite',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nametype', models.CharField(max_length=20)),
                ('recclass', models.CharField(max_length=50)),
                ('mass', models.FloatField()),
                ('fall', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
