# Generated by Django 5.2 on 2025-04-27 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meteorite',
            fields=[
                ('name', models.CharField(max_length=100, unique=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nametype', models.CharField(max_length=20)),
                ('recclass', models.CharField(max_length=50)),
                ('mass', models.FloatField()),
                ('fall', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('usertype', models.CharField(choices=[('admin', 'Admin'), ('normal', 'Normal')], max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('reg_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meteorite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteorite.meteorite')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meteorite.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meteorite.user'),
        ),
    ]
